
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDErightNEGrightPOWERDIVIDE ENDLINE ERR LPAREN MINUS NUMBER PLUS POWER RPAREN TIMESline : exp ENDLINEline : error ENDLINEexp : numnum : NUMBERnum : MINUS NUMBER %prec NEGexp : exp PLUS expexp : exp MINUS expexp : exp TIMES expexp : exp DIVIDE expexp : LPAREN exp RPARENexp : MINUS LPAREN exp RPAREN %prec NEGexp : exp POWER powexpexp : MINUS MINUS exppowexp : pownumpownum : NUMBERpownum : MINUS NUMBER %prec NEGpowexp : powexp PLUS powexppowexp : powexp MINUS powexppowexp : powexp TIMES powexppowexp : powexp DIVIDE powexppowexp : LPAREN powexp RPARENpowexp : MINUS LPAREN powexp RPAREN %prec NEGpowexp : MINUS MINUS powexp'
    
_lr_action_items = {'error':([0,],[3,]),'LPAREN':([0,5,6,9,10,11,12,13,15,16,25,26,31,32,33,34,35,36,],[6,16,6,6,6,6,6,26,6,6,36,26,26,26,26,26,26,26,]),'MINUS':([0,2,4,5,6,7,9,10,11,12,13,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,],[5,10,-3,15,5,-4,5,5,5,5,25,5,5,-5,10,-6,-7,-8,-9,-12,-14,35,25,-15,-13,10,-10,25,25,25,25,25,25,-16,32,-11,-17,-18,-19,-20,-23,32,-21,-22,]),'NUMBER':([0,5,6,9,10,11,12,13,15,16,25,26,31,32,33,34,35,36,],[7,17,7,7,7,7,7,27,7,7,37,27,27,27,27,27,27,27,]),'$end':([1,8,14,],[0,-1,-2,]),'ENDLINE':([2,3,4,7,17,19,20,21,22,23,24,27,28,30,37,39,40,41,42,43,44,46,47,],[8,14,-3,-4,-5,-6,-7,-8,-9,-12,-14,-15,-13,-10,-16,-11,-17,-18,-19,-20,-23,-21,-22,]),'PLUS':([2,4,7,17,18,19,20,21,22,23,24,27,28,29,30,37,38,39,40,41,42,43,44,45,46,47,],[9,-3,-4,-5,9,-6,-7,-8,-9,-12,-14,-15,-13,9,-10,-16,31,-11,-17,-18,-19,-20,-23,31,-21,-22,]),'TIMES':([2,4,7,17,18,19,20,21,22,23,24,27,28,29,30,37,38,39,40,41,42,43,44,45,46,47,],[11,-3,-4,-5,11,11,11,-8,-9,-12,-14,-15,11,11,-10,-16,33,-11,33,33,-19,-20,33,33,-21,-22,]),'DIVIDE':([2,4,7,17,18,19,20,21,22,23,24,27,28,29,30,37,38,39,40,41,42,43,44,45,46,47,],[12,-3,-4,-5,12,12,12,-8,-9,-12,-14,-15,12,12,-10,-16,34,-11,34,34,-19,-20,34,34,-21,-22,]),'POWER':([2,4,7,17,18,19,20,21,22,23,24,27,28,29,30,37,39,40,41,42,43,44,46,47,],[13,-3,-4,-5,13,13,13,13,13,-12,-14,-15,13,13,-10,-16,-11,-17,-18,-19,-20,-23,-21,-22,]),'RPAREN':([4,7,17,18,19,20,21,22,23,24,27,28,29,30,37,38,39,40,41,42,43,44,45,46,47,],[-3,-4,-5,30,-6,-7,-8,-9,-12,-14,-15,-13,39,-10,-16,46,-11,-17,-18,-19,-20,-23,47,-21,-22,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'line':([0,],[1,]),'exp':([0,6,9,10,11,12,15,16,],[2,18,19,20,21,22,28,29,]),'num':([0,6,9,10,11,12,15,16,],[4,4,4,4,4,4,4,4,]),'powexp':([13,26,31,32,33,34,35,36,],[23,38,40,41,42,43,44,45,]),'pownum':([13,26,31,32,33,34,35,36,],[24,24,24,24,24,24,24,24,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> line","S'",1,None,None,None),
  ('line -> exp ENDLINE','line',2,'p_line','calcyacc.py',53),
  ('line -> error ENDLINE','line',2,'p_line_error','calcyacc.py',60),
  ('exp -> num','exp',1,'p_exp_num','calcyacc.py',66),
  ('num -> NUMBER','num',1,'p_num_plus','calcyacc.py',72),
  ('num -> MINUS NUMBER','num',2,'p_num_minus','calcyacc.py',76),
  ('exp -> exp PLUS exp','exp',3,'p_exp_add','calcyacc.py',81),
  ('exp -> exp MINUS exp','exp',3,'p_exp_sub','calcyacc.py',87),
  ('exp -> exp TIMES exp','exp',3,'p_exp_mul','calcyacc.py',93),
  ('exp -> exp DIVIDE exp','exp',3,'p_exp_div','calcyacc.py',99),
  ('exp -> LPAREN exp RPAREN','exp',3,'p_exp_paren_plus','calcyacc.py',112),
  ('exp -> MINUS LPAREN exp RPAREN','exp',4,'p_exp_paren_minus','calcyacc.py',116),
  ('exp -> exp POWER powexp','exp',3,'p_exp_pow','calcyacc.py',122),
  ('exp -> MINUS MINUS exp','exp',3,'p_exp_double_minus','calcyacc.py',128),
  ('powexp -> pownum','powexp',1,'p_powexp_num','calcyacc.py',134),
  ('pownum -> NUMBER','pownum',1,'p_pownum_plus','calcyacc.py',140),
  ('pownum -> MINUS NUMBER','pownum',2,'p_pownum_minus','calcyacc.py',144),
  ('powexp -> powexp PLUS powexp','powexp',3,'p_powexp_add','calcyacc.py',150),
  ('powexp -> powexp MINUS powexp','powexp',3,'p_powexp_sub','calcyacc.py',156),
  ('powexp -> powexp TIMES powexp','powexp',3,'p_powexp_mul','calcyacc.py',162),
  ('powexp -> powexp DIVIDE powexp','powexp',3,'p_powexp_div','calcyacc.py',168),
  ('powexp -> LPAREN powexp RPAREN','powexp',3,'p_powexp_paren_plus','calcyacc.py',181),
  ('powexp -> MINUS LPAREN powexp RPAREN','powexp',4,'p_powexp_paren_minus','calcyacc.py',185),
  ('powexp -> MINUS MINUS powexp','powexp',3,'p_powexp_double_minus','calcyacc.py',192),
]
